name: ChunkSpawnerLimit
version: ${project.version}
main: com.phanaticmc.chunkspawnerlimit.ChunkSpawnerLimit
authors: [PhanaticD]
description: Limit the amount of spawners by chunk
api-version: 1.13
commands:
  spawnerlist:
    description: lists spawners
    usage: /spawnerlist
    permission: chunkspawnerlimit.list
  spawnerdelete:
    description: deletes spawners
    usage: /spawnerdelete
    permission: chunkspawnerlimit.delete
permissions:
  chunkspawnerlimit.list:
    description: Allows list command
    default: op
  chunkspawnerlimit.delete:
    description: Allows delete command
    default: op